#!/usr/bin/env zsh
source $HOME/.config/zsh/.zshrc
BRANCH=$(git branch --show-current)

if [[ $BRANCH =~ "^([a-z]+)/([A-Z]+-[0-9]+)" ]]; then
    PREFIX="${match[1]}: ${match[2]} "
else
    PREFIX=""
fi

echo 'Commit and Push all changes.\n'
echo 'Commit Message:'
COMMIT=$PREFIX
vared -M emacs COMMIT
git add --all
echo '\n'
git commit -m $COMMIT --no-verify
echo '\n'
git push --no-verify
echo '\n Done.'
read
