#!/usr/bin/env zsh
source $HOME/.config/zsh/.zshrc

function commit(){
  echo "Commiting..."
  echo 'Commit Message:'
  git add --all
  COMMIT=""
  vared -M emacs COMMIT
  echo '\n'
  git commit -m $COMMIT --no-verify
}

function push(){
  echo "Pushing..."
  git push --no-verify
}

 function force_push(){
  echo "Force Pushing..."
  git push --force --no-verify
}

function dry_push(){
  echo "Dry Pushing..."
  git push --dry-run
}

OPTS="Commit and Push
Commit
Push
Force Push
Dry Push"

case $(echo $OPTS | fzf) in
    Commit) commit;;
    Push) push;;
    "Commit and Push") commit && push;;
    "Force Push") force_push;;
    "Dry Push") dry_push;;
    *) echo "Invalid option";;
esac
echo "\n✅ Done."
read

