return function(c, g, options, util)
	return {
		BufferCurrent = { bg = g.bg.base, fg = g.fg.base },
		BufferCurrentERROR = { bg = g.bg.base, fg = g.semantic.error },
		BufferCurrentHINT = { bg = g.bg.base, fg = g.semantic.hint },
		-- BufferCurrentIcon = { bg = g.bg.base, fg = c.},
		BufferCurrentINFO = { bg = g.bg.base, fg = g.semantic.info },
		BufferCurrentWARN = { bg = g.bg.base, fg = g.semantic.warning },
		BufferCurrentIndex = { bg = g.bg.base, fg = g.semantic.info },
		BufferCurrentMod = { bg = g.bg.base, fg = g.semantic.warning },
		BufferCurrentSign = { bg = g.bg.base, fg = g.fg.base },
		BufferCurrentTarget = { bg = g.bg.base, fg = c.red },
		BufferAlternate = { bg = g.bg.lower, fg = g.fg.base },
		BufferAlternateERROR = { bg = g.bg.lower, fg = g.semantic.error },
		BufferAlternateHINT = { bg = g.bg.lower, fg = g.semantic.hint },
		-- BufferAlternateIcon = { bg = g.bg.lower, fg = c. },
		BufferAlternateIndex = { bg = g.bg.lower, fg = g.semantic.info },
		BufferAlternateINFO = { bg = g.bg.lower, fg = g.semantic.info },
		BufferAlternateMod = { bg = g.bg.lower, fg = g.semantic.warning },
		BufferAlternateSign = { bg = g.bg.lower, fg = g.semantic.info },
		BufferAlternateTarget = { bg = g.bg.lower, fg = c.red },
		BufferAlternateWARN = { bg = g.bg.lower, fg = g.semantic.warning },
		BufferVisible = { bg = g.editor.statusline, fg = g.fg.base },
		BufferVisibleERROR = { bg = g.editor.statusline, fg = g.semantic.error },
		BufferVisibleHINT = { bg = g.editor.statusline, fg = g.semantic.hint },
		-- BufferVisibleIcon = { bg = g.editor.statusline, fg = c. },
		BufferVisibleINFO = { bg = g.editor.statusline, fg = g.semantic.info },
		BufferVisibleWARN = { bg = g.editor.statusline, fg = g.semantic.warning },
		BufferVisibleIndex = { bg = g.editor.statusline, fg = g.semantic.info },
		BufferVisibleMod = { bg = g.editor.statusline, fg = g.semantic.warning },
		BufferVisibleSign = { bg = g.editor.statusline, fg = g.semantic.info },
		BufferVisibleTarget = { bg = g.editor.statusline, fg = c.red },
		BufferInactive = { bg = util.darken(g.bg.highlight, 0.4), fg = util.darken(c.dark5, 0.8) },
		BufferInactiveERROR = { bg = util.darken(g.bg.highlight, 0.4), fg = util.darken(g.semantic.error, 0.8) },
		BufferInactiveHINT = { bg = util.darken(g.bg.highlight, 0.4), fg = util.darken(g.semantic.hint, 0.8) },
		-- BufferInactiveIcon = { bg = g.editor.statusline, fg = util.darken(c., 0.1) },
		BufferInactiveINFO = { bg = util.darken(g.bg.highlight, 0.4), fg = util.darken(g.semantic.info, 0.8) },
		BufferInactiveWARN = { bg = util.darken(g.bg.highlight, 0.4), fg = util.darken(g.semantic.warning, 0.8) },
		BufferInactiveIndex = { bg = util.darken(g.bg.highlight, 0.4), fg = c.dark5 },
		BufferInactiveMod = { bg = util.darken(g.bg.highlight, 0.4), fg = util.darken(g.semantic.warning, 0.8) },
		BufferInactiveSign = { bg = util.darken(g.bg.highlight, 0.4), fg = g.bg.base },
		BufferInactiveTarget = { bg = util.darken(g.bg.highlight, 0.4), fg = c.red },
		BufferOffset = { bg = g.editor.statusline, fg = c.dark5 },
		BufferTabpageFill = { bg = util.darken(g.bg.highlight, 0.8), fg = c.dark5 },
		BufferTabpages = { bg = g.editor.statusline },
	}
end
